### ISSUE TITLE
Failing to install PhantomJS 2.0.0

### ISSUE THREAD

**Issue by opb** [jakoch/phantomjs-installer#12]
Hi there

I'm using this package with laravel, deployed via rocketeer. It has worked flawlessly up until PhantomJS was updated to 2.0.0. Now I'm seeing the following errors when composer runs its `post-install` commands:

```
[www-data@178.79.130.253:7987] (production-server) Generating autoload files
[www-data@178.79.130.253:7987] (production-server) Generating optimized class loader
[www-data@178.79.130.253:7987] (production-server) Compiling common classes
[www-data@178.79.130.253:7987] (production-server) Compiling views
[www-data@178.79.130.253:7987] (production-server) - Installing phantomjs (2.0.0)
[www-data@178.79.130.253:7987] (production-server) Downloading: connection...
[www-data@178.79.130.253:7987] (production-server) Script PhantomInstaller\Installer::installPhantomJS handling the post-install-cmd event terminated with an exception
[www-data@178.79.130.253:7987] (production-server) 
[www-data@178.79.130.253:7987] (production-server) 
[www-data@178.79.130.253:7987] (production-server) 
[www-data@178.79.130.253:7987] (production-server) [Composer\Downloader\TransportException]
[www-data@178.79.130.253:7987] (production-server) The "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2" file could not be downloaded (HTTP/1.1 404 NOT FOUND)
```

Please let me know if you need any further information.

Thanks!

EDIT: I'm using dev-master, will drop version for now.

**Comment by jakoch** [comment]
Hey Olly!

Thanks for reporting the issue.
Uff, i thought the new version is out, because the website states "Download v2.0".
But it's only true for Windows and Mac releases.
For the linux version the website (http://phantomjs.org/download.html) states:
> Linux
> Binary packages for Linux are still being prepared. There are still issues to be solved until a static
> build is available (see issue 12948 for more details).

Possible solutions:
- I could y introduce a fallback to v1.9.8 when v2.0.0 linux releases are required.
- We could wait until the "linux-x86_64" packages arrives and meanwhile specify an older version of the phantomjs-installer in your `composer.json`:

    "require": {
        "jakoch/phantomjs-installer": "1.9.8"
    },

- I could revert release tag v2.0.0 back to v1.9.8 - and reapply it, when they are ready.

I think the best solution would be to simply revert it. What do you think?

**Comment by jakoch** [comment]
> EDIT: I'm using dev-master, will drop version for now.

Ok. I leave the issue open for others running into this.

**Comment by Sorbing** [comment]
Faced with the same problem .. Thanks for the clarification.

**Comment by mycrewguide** [comment]
Any update on this?  I'm getting the same error when using dev-master

**Comment by mycrewguide** [comment]
For further info, this is what I'm getting when attempting to install my project using Laravel Forge:

Generating autoload files
Generating optimized class loader
Compiling common classes
  - Installing phantomjs (2.0.0)
    Downloading: Connecting...Script PhantomInstaller\Installer::installPhantomJS handling the post-install-cmd event terminated with an exception


                                                                                                                                                    
  [Composer\Downloader\TransportException]                                                                                                          
  The "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2" file could not be downloaded (HTTP/1.1 404 NOT FOUND)

**Comment by jakoch** [comment]
No update on this. They are still in this disastrous state of the PhantomJS project.

It's quite impressive how such a widely used project gets stuck, when the Continuous Integration stops compiling / working and the maintainer starts to work on other projects. It seems that Travis-CI is not able to build PhantomJS, because the boxes provide only ~4GB memory. PhantomJS is build on a patched Qt framework and this build really draws on memory and build time. I think there will be no progress in this area, unless they upgrade their CI package at Travis to professional (in order to get more mem) or switch their CI service AND more important: the two maintainers find more time to get the project back on track. They could also decide to split out the framework build and pull the dependencies in.

**Comment by zedtux** [comment]
+1 I'm encountering the same issue and indeed thank you @jakoch for the details about the issue !

**Comment by pablomoreno61** [comment]
Same problem here, this is my error

  - Installing phantomjs (2.0.0)
    Downloading: Connecting...Script PhantomInstaller\Installer::installPhantomJS handling the post-update-cmd event terminated with an exception
                                                                                                                                   
  [Composer\Downloader\TransportException]                                                                                                          
  The "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2" file could not be downloaded (HTTP/1.1 404 NOT FOUND)

**Comment by JarJak** [comment]
same problem

**Comment by jakoch** [comment]
Unfortunately the situation of the phantomjs project itself is unchanged.. :(

**Comment by JarJak** [comment]
it would propose marking 2.0 branch as dev since it is not really
stable/usable, so composer will get 1.9.* as default

2015-09-04 19:52 GMT+02:00 Jens A. Koch <notifications@github.com>:

**Comment by halfer** [comment]
Same problem here, but I don't _need_ 2.0.0 - I'll lock to 1.9.8 for the time being. Thanks for your work on this.

**Comment by jakoch** [comment]
Yes, locking to 1.9.8 is the right thing. I still hope that the Phantom team gets another release out this year, but Ariya spends his limited time working on [Esprima](http://esprima.org/). :/

(By the way: I've seen your nickname a couple of times over at SO and read your "[I ♥ PHP](http://ilovephp.jondh.me.uk/)" tutorial. 
I have lots of respect for the work you do, because it takes quite a lot of time to put together a well written, structured tutorial (and to maintain it). The diff-style is helpful, because the reader can participate in the evolution of the project. Haven't seen that in a tutorial before. It's great!)

**Comment by halfer** [comment]
@jakoch, thanks! It was more work than I expected, certainly. I don't do so much work on it now, as it is doesn't get as much attention/feedback as I thought it might - I think it needs some promotion. Might do some more work on it, or a follow-up tutorial, in the future :smile:

**Comment by jakoch** [comment]
Update: seems **PhantomJS v2.1** is slowly cooking up..
- https://github.com/Vitallium/phantomjs/releases
- https://groups.google.com/forum/#!topic/phantomjs-dev/vkdGvFpULNo

**Comment by jakoch** [comment]
Update: **PhantomJS v2.1.1** was released. 
Downloads: http://phantomjs.org/download.html

Adjusting the hardcoded bits of the installer accordingly...

**Comment by jakoch** [comment]
Update: **PhantomJS v2.1.1** was released - http://phantomjs.org/download.html

I've adjusted the installer to fetch the latest version and tagged a new release:
https://github.com/jakoch/phantomjs-installer/releases/tag/2.1.1

Best, Jens

**Comment by JarJak** [comment]
Please update composer.json file, it stiil requires
```
    "require": {
        "jakoch/phantomjs-installer": "2.0.0"
    },
```
