### ISSUE TITLE
Create a link instead of copying the bin

### ISSUE THREAD

**Issue by brad-jones** [jakoch/phantomjs-installer#14]
Not sure if there are other issues that I am not thinking of but can we just create a sym link to the downloaded binary?

Just like composer does with a normal package that defines a binary in it's composer.json.

Weighing in at nearly 40Mb it's not like it's a super small.

**Comment by jakoch** [comment]
Good idea! But not easy to implement, because symlinks have a lot of cross-platform edge cases.
Composer has this functionality somewhere in the LibraryInstaller - installBinaries().
https://github.com/composer/composer/blob/master/src/Composer/Installer/LibraryInstaller.php#L191
I'll try to base a solution on their API.

**Comment by brad-jones** [comment]
Had an idea over night, you could just delete the original version after copying it to the composer bin dir. Slightly hacky way of doing it but much easier to implement.

**Comment by drAlberT** [comment]
fabpot/php-cs-fixer makes a symlink  ..  as it is from FabPot I think it does it the right way .. you can take a look to it and see if it has the solution :)

**Comment by jakoch** [comment]
@drAlberT Please post a link to the relevant pieces of source code. I will then take a look. Thank you.

Update to my last post in this thread:
The Composer guys cleaned their LibraryInstaller a bit and split the "proxyCode" functions out into a BinaryInstaller, see https://github.com/composer/composer/blob/761d6a549c229befce49863bf3d282b4a35bbbbe/src/Composer/Installer/BinaryInstaller.php

**Comment by drAlberT** [comment]
@jakoch I think `php-cs-fix` achieves the task simply declaring it in composer `"bin":` section .. but I'm afraid this approach would not work in this case because the phantomjs binary is downloaded separately in the update hook ...

Maybe adding a composer.json declaring `"bin": "bin/phantomjs"` in `vendor/jakoch/phantomjs` could do the trick ?!?

**Comment by jakoch** [comment]
We stick to copying, but changed the strategy a bit, to replace the binary of a running process 
by copying to a temp file first, then renaming it. See #18.

Closing.
