### ISSUE TITLE
Issue installing PJS on Amazon Linux In Docker locally

### ISSUE THREAD

**Issue by mjgorman** [jakoch/phantomjs-installer#30]
```
> PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (2.1.1)
    Authentication required (bbuseruploads.s3.amazonaws.com):
      Username: 
      Password: 
  - Installing phantomjs (2.1.1)
    Downloading: Connecting...    Downloading: Connecting...    Downloading: Connecting...  - Installing phantomjs (2.1.1)
    Downloading: Connecting...    Downloading: Connecting...    Downloading: Connecting...
```

I suspect this is because it tries to do something special for Amazon Linux and running in docker is interfering, just like you can't install packages on Amazon linux if its not inside the Amazon infrastructure. 

Is it possible to tell the installer to target a non amazon linux version, so that I can use this locally in a docker instance for my development team? If they run the composer outside of the docker instance its fine, but obviously gives them the mac version of PJS not linux which we need.

**Comment by jakoch** [comment]
Hey Michael!

Thank you for reporting this issue. 

> Is it possible to tell the installer to target a non amazon linux version, so that I can use this locally in a docker instance for my development team?

This sounds like you want to force/set the platform requirement for the install script manually, right?
No, that's not possible, yet. We could try to improve the OS detection or force it.

> If they run the composer outside of the docker instance its fine, but obviously gives them the mac version of PJS not linux which we need.

The question is why does it "obviously give the mac version"?

The OS detection used by the installer is pretty simple and based on `php_uname()`, see https://github.com/jakoch/phantomjs-installer/blob/master/src/PhantomInstaller/Installer.php#L383

Possible problems: the function `php_uname()` is disabled or it doesn't contain "linux" as part of string. 
I simply don't know what the output of that function is on your setup.
It would be nice, if you could post its output.

Alternatively, we could base the detection on an environment variable instead of using `php_uname`.
Either an existing one or a manually set one, maybe `$_SERVER["phantomjs_installer_os"]`.

Would that work? Looking forward hearing your suggestions.
Yours, Jens

**Comment by mjgorman** [comment]
Sorry. I should have been more descriptive on our setup. 

The development team used to develop locally on their Mac. So running composer there grabs the mac binaries which causes problem when the app goes to use phantomjs. Now they develop in Docker (Amazon Linux based) so its more production like. Docker however receives that error when trying to download. 

OS detection was a red herring. I hadn't had a chance to look through your code, which i've now done and I see it does detect properly as linux, you have no special rules outside of it being linux and 32/64bit. The download looks like it is somehow loosing the amazon key and secret being appended to the url from bitbucket over to AWS s3 where its hosted. 

I'm not sure what about Docker would cause this to happen. It sees to work fine on our linux build servers where the apps are normally packaged for release.

**Comment by jakoch** [comment]
No worries. 

> The download looks like it is somehow loosing the amazon key and secret being appended to the url from bitbucket over to AWS s3 where its hosted.

Boils down to: do downloads always fail or just sometimes...

Sometimes the downloads from bitbucket are simply unreliable and you'll get a 403 - for whatever reason (bandwidth or rate limit hit). Because of the download issues, there is now a big discussion in progress (over at the PhantomJS tracker - https://github.com/ariya/phantomjs/issues/ 13953) about  finding an alternative hosting location or a mirror system for the official downloads.

For instance, the guys from Medium started to host the Phantom downloads themself,
see https://github.com/Medium/phantomjs/releases/tag/v2.1.1
That is also the download source used by the [NPM package phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt).

They have a config directive `phantomjs_cdnurl`, which allows to set the download source (base url).
I could introduce the same concept to allow and support other download locations.

I'm a bit reluctant to add non official mirrors. I would have to add and compare hashes to make sure that nobody messes around with the packages: even more work.

**Comment by jakoch** [comment]
I will add two env variables `PHANTOMJS_PLATFORM` (to set the target platform) and `PHANTOMJS_ARCH` (to set the target architecture) to bypass the automatic OS detection.
This is for cases, where you know in advance that you want to install PhantomJS for a specific architecture. For instance to build a deployment package for Linux on Mac.

**Comment by jakoch** [comment]
Do the constants meet your use case?

**Comment by mjgorman** [comment]
Yeah. I'd say so.

**Comment by jakoch** [comment]
:+1: 
A new release is out: https://github.com/jakoch/phantomjs-installer/releases/tag/2.1.1-p03
