### ISSUE TITLE
Binary download starts multiple times

### ISSUE THREAD

**Issue by stefanzweifel** [jakoch/phantomjs-installer#32]
Hey there

I know this might be a duplicate to #31 but those comments didn't help me. 😞 
The `post-update-cmd` doesn't install the binary in the `bin` nor in the `vendor/bin` folder. The strange thing is that the download starts multiple times (see log below).

My composer.json

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/stefanzweifel/php-phantomjs"
        }
    ],
    "require": {
        ...
        "jonnyw/php-phantomjs": "dev-master",
    },
    "scripts": {
        "post-install-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ],
        "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ]
    },
    "config": {
        "bin-dir": "vendor/bin"
    }
}
```

I use my own [fork of jonnyw/php-phantomjs](https://github.com/stefanzweifel/php-phantomjs/commit/f62b510156bc4adafa44852a5140c417f3c07bd4), so I can use your newest release `2.1.1-p4`.

Now if I deploy my app or update dependencies on my linux boxes, I see the following output (verbose mode activated).

```bash
> post-update-cmd: PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (2.1.1)
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    Downloading: 100%
    Extracting archive
  - Installing phantomjs (2.1.1)
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    Downloading: 100%
    Extracting archive
  - Installing phantomjs (2.1.1)
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    Downloading: 100%
    Extracting archive
  - Installing phantomjs (2.1.1)
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    Downloading: 100%
    Extracting archive
```

This only happens in my local environment where I use [laravel/homestead](https://github.com/laravel/homestead) and on my production server which is a Digital Ocean Droplet with Ubuntu 16.04. I'm also running php7.0 everywhere.

If I run `composer run-script post-update-cmd` in my host system (OS X) the binary get's downloaded correctly.

**It don't use our package directly. I use [jonnnnyw/php-phantomjs](https://github.com/jonnnnyw/php-phantomjs), but the error comes from your package. That's why I created the issue here.**

Does anyone might have a solution to this problem?

---

My current workaround is `wget` the binary from bitbucket and extracting / moving it with shell commands. But I think it would be better, if I could use the built in downloader :)

**Comment by stefanzweifel** [comment]
I dig through the Installer class and found the root of the problem.


The download starts 4 times, because the installer tries to install older versions of phantom-js. Currently there are 4 versions available. [Link to loop](https://github.com/jakoch/phantomjs-installer/blob/a093285dd43d955cc11d0379ea53df0fff5681a8/src/PhantomInstaller/Installer.php#L130-L132)

Second, only the `\Composer\Downloader\TransportException` gets catched. The installer fails silently if something else happens. In my case the bz2 extensions is not activated:

`"unable to decompress bzipped phar archive 
"/home/vagrant/code/project/vendor/jakoch/phantomjs/b82b82cf21fc412368fb8125c6a39f11.bz2" to temporary file, enable bz2 extension in php.ini`

I digg further ...

**Comment by jakoch** [comment]
Hey Stefan!
Thank you for reporting this issue.

The automatic version lowering for downloads kicks in and downloads are retried, not because the transport itself failed, but the extraction of the downloaded archive (because of the missing/not loaded `bz2` extension).

We could do two things to address this issue:

1. We could check with `extension_loaded bz2` at the top inside `installPhantomJS()` and exit early. We have to take a special case for Windows into account, where this extension isn't needed, because zip file, not tar.gz.

2. Or add another catch inside `download()`, this time for a more unspecialized exception - so that the extraction error catched. But then the already downloaded file dangles somewhere in a Composer or main temp folder.. not so good.

(If i remember correctly, it was a normal catch all, before i merged a patch to catch the TransportException. Grr.)

I guess i will go with 1 and add the extension_loaded() check and then output a message.

**Comment by jakoch** [comment]
> But I would like to create a PR, so every error get's reported to the CLI. Is that okay for you?

Of course! I would be happy to add your PR.

**Comment by stefanzweifel** [comment]
Will get right to it. 🎉
