### ISSUE TITLE
Bitbucket OAuth required?

### ISSUE THREAD

**Issue by mbrodala** [jakoch/phantomjs-installer#34]
After adding this package I noticed that the 2nd installation attempt gives me this:

```
> PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (2.1.1)
    Downloading: Connecting...
Could not fetch https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2, please create a bitbucket OAuth token to to go over the API rate limit
Follow the instructions on https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html
to create a consumer. It will be stored in "/home/.../.composer/auth.json" for future use by Composer.
Ensure you enter a "Callback URL" or it will not be possible to create an Access Token (this callback url will not be used by composer)
Consumer Key (hidden):
Consumer Secret (hidden):
Consumer stored successfully.
```

Is this really required or simply a Bitbucket issue?

**Comment by jakoch** [comment]
Hey!

No, it's not required. Bitbucket is simply unreliable sometimes.
Others devs are running into this issue, too, e.g. https://github.com/acquia/blt/issues/223
The main issue is https://github.com/ariya/phantomjs/issues/13953

**How could a solution look like?**
We could introduce a configuration directive to select an alternative download location
and provide multiple arrays with mirror download locations.
One mirror, for instance, could be https://cnpmjs.org/downloads
(We could also randomize the mirror selection.)
That's the easy part...

We would also need to add signature checks for these unofficial downloads.
The problem is, that the upstream (Ariya and his team) does not provide them.
Well, that's the complicated part...

**Comment by mbrodala** [comment]
Thanks for explaining the issue at hand. I see that the checksums are mentioned in the docs starting with [this change](https://github.com/ariya/phantomjs/commit/6a127b5e25a091eff431c5efe06db5e1389099fe) but for automated downloads the checksums must be provided as additional files.

Could you ask them to add these files to their download list on Bitbucket?

**Comment by jakoch** [comment]
> .. but for automated downloads the checksums must be provided as additional files

Yes, i could maintain the checksums in the installer, but that's inconvenient and just adds more maintenance work for me.

> Could you ask them to add these files to their download list on Bitbucket?

Ok, let's do that. It would help me, other installer authors and all mirroring guys.
https://github.com/ariya/phantomjs/issues/14440

**Comment by mbrodala** [comment]
Thanks a lot, let's see how it goes.

**Comment by tuxayo** [comment]
I case anyone is wondering (it took me a moment to read carefully enough and understand it).
**Retry the install**, these are intermittent issues.

**Comment by jakoch** [comment]
I've added the environment and server variable `PHANTOMJS_CDNURL`, 
which enables you to set a mirror URL. 
You find the documentation in the Readme:
 https://github.com/jakoch/phantomjs-installer#downloading-from-a-mirror

The new feature is available on the `dev-master` branch.
Please give me a feedback, if this works for you.

(Checks for the file hashes are not implemented, yet.)

**Comment by mbrodala** [comment]
Since two of the CDNs are Chinese they are not really an option for wide deployments.

However, I had some success getting PhantomJS installed thanks to [Medium/phantomjs](https://github.com/Medium/phantomjs).

**Comment by jakoch** [comment]
Thank you for testing and providing feedback.

I've updated the ReadMe and added the locations of the mirrors.
Actually, you can set any mirror URL you find. The CDNURLs are not hardcoded.
With one exception: Github URLs need a bit of hardcoding, because their folders are versioned.

I've tagged a new release: [v2.1.1-p06](https://github.com/jakoch/phantomjs-installer/releases/tag/2.1.1-p06)

**Comment by mbrodala** [comment]
@jakoch Thanks a lot. As soon as the issues on our CI are sorted out, I'll give your installer another try. ;-)

**Comment by tuxayo** [comment]
@mbrodala
> Since two of the CDNs are Chinese they are not really an option for wide deployments.

You mean that the bandwidth wont be suitable for the majority of users which are out of asia?

**Comment by mbrodala** [comment]
@tuxayo Yes, that's an issue since everything from inside of Chine must pass the big firewall.
