### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by jralph** [jakoch/phantomjs-installer#39]
Just looking at the versioning of the project, there seem to be a lot of `2.1.1-pXX` versions. Are these `p` versions patches?

If so, wouldn't it make more sense to increment the 2.1.x instead? So `2.1.1-p06` would become `2.1.6`.

**Comment by jakoch** [comment]
Hey!

The main version of the package (e.g. `2.1.1`) indicates the PhantomJS version you want to install.
Composer fetches the 2.1.1 tag(!) of the installer. The installer fetches the 2.1.1 version of PhantomJS.
See also "[How to require specific versions of phantomjs](https://github.com/jakoch/phantomjs-installer#how-to-require-specific-versions-of-phantomjs)".

I'm using patch version suffixes `-pXY` to indicate new releases of the installer itself, 
while keeping the main version PhantomJS: `<version-phantomjs>-p<version-phantomjs-installer>`.

I'm open for suggestions, but i want to keep the phantomjs version in the versioning string of the package to indicate that clearly in `composer.json`. Not sure, if another versioning concept would work out, e.g. `2.1.6-2.1.1` (`<phantomjs-installer-version>-<phantomjs-version>`).

**Comment by jralph** [comment]
Ahh that makes sense. Guess its tougher trying to match your versions to versions of another product.

Cheers!

**Comment by pjona** [comment]
I think there is some misunderstanding in `README.md`:

> The version number of the package specifies the PhantomJS version. When you specify:
^2.1: Composer fetches the latest installer version above v2.1. The installer fetches the latest version of PhantomJS.
2.1.1-p07: Composer fetches the 2.1.1-p07 tag of the installer. The installer fetches the 2.1.1 version of PhantomJS.

So after reading this I want get latest version of installer, so I choose `^2.1`. I put `"jakoch/phantomjs-installer": "^2.1"` to the composer.json, and run `composer install`. After this in `composer.lock` I get:

```
{
    "name": "jakoch/phantomjs-installer",
    "version": "2.1.1",
    "source": {
        "type": "git",
        "url": "https://github.com/jakoch/phantomjs-installer.git",
        "reference": "b8ee2aac9b95f9a9ee30a05a4df4a0984a8a8b85"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/jakoch/phantomjs-installer/zipball/b8ee2aac9b95f9a9ee30a05a4df4a0984a8a8b85",
        "reference": "b8ee2aac9b95f9a9ee30a05a4df4a0984a8a8b85",
        "shasum": ""
    },
    ...
}
```

I expect I will be download `2.1.1-p07`, because this is the latest version. It should works like this?

**Comment by pjona** [comment]
After changing from `^2.1` to `2.1.1-p07`, and run `composer update` it works:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing jakoch/phantomjs-installer (2.1.1)
  - Installing jakoch/phantomjs-installer (2.1.1-p07)
    Downloading: 100% 
```

If it's not error, maybe I can send PR to change `README.md` to make it more readable.

**Comment by jakoch** [comment]
Good catch, Marek! 👍 


I used a simple exact versioning in the Readme for a very long time, e.g. `2.1.1-p07` to fetch the installer.
But i've messed it up once more :( by switching to `^2.1`, because i was of the opinion, that Composer would resolve the patch version in historically correct order. It handles and orders the patch levels before version `2.1.1` and not on top, see also [SemVerChecker](https://semver.mwl.be/#?package=jakoch%2Fphantomjs-installer&version=%5E2.1&minimum-stability=stable). 

If you know a solution, with wildcard/caret/range operator which correctly resolves crazy patch levels version, please let me know.

For now i will revert to exact versioning.
