### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by gsouf** [jakoch/phantomjs-installer#44]
Hi, 

The installer has had a few improvment that make it less prone to error. Espacially by specifying  ext-bz2 as a requirement.

Can you bump a new version, please?

**Comment by jakoch** [comment]
Hey!

There is only [one commit](https://github.com/jakoch/phantomjs-installer/compare/2.1.1-p08...master) on-top/ahead of the current version `2.1.1-p08` and that is an update to the Changelog. I don't want to bump version for that tiny change.

Regarding the `ext-bz2` requirement:  it landed with [2.1.1-p01 - 2016-04-12](https://github.com/jakoch/phantomjs-installer/blob/master/Changelog.md#211-p01---2016-04-12). You should be fine, when you require any version above `2.1.1-p01`.

**Comment by gsouf** [comment]
I didn't notice that versions "-pXX" were ahead of 2.1.1.

 In my composer.json I'm on "~2.1.1" and composer is not able to update by itself to the last version.  According to semver where""X.Y.Z" is the current version, for patches like that, I think you just should increment "Z" by 1 instead of doing -pXX, not sure about the last statement because I actually never used this syntax.

**Comment by jakoch** [comment]
Yes, well know issue: https://github.com/jakoch/phantomjs-installer/issues/39
Yes, the `-pXX` version are indeed ahead of `2.1.1`, see also [SemVerChecker](https://semver.mwl.be/#?package=jakoch%2Fphantomjs-installer&version=~2.1&minimum-stability=stable). I don't know why Composer doesn't resolve them.

I've tried to explain the version hack i use in the Readme. 
Basically, the `2.1.1` signals the version of the PhantomJS installer you are trying to install,
It's two versions in one ;) 
I can't increase the Patch level version to `2.1.2`, because that PhantomJS version doesn't exist.

**Comment by gsouf** [comment]
Thanks for explanation @jakoch,  that makes a lot of sense now.

I'm not sure I fully understood the spec, but according to semver documentation, it looks like build meta data have always a lower precedence than the same version without build metadata. [See 10 and 11](http://semver.org/#spec-item-10)

I think the solution to make it more constant in the repository is to not use build meta data free version.

For instance for version 2.1.2 you could stard with ``2.1.2-p01`` instead of ``2.1.2`` alone.

**Comment by jakoch** [comment]
Thank you for diving into the SemVer Spec and finding the relevant sections. 

Ok, let's see... Section 10 (build metadata) says

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version.

We don't have a plus sign, so it's not build meta data.

I think it's Section 9. The version we have is a pre-release version denoted by appending a hyphen. 
`Maj.Min.Patch-PreReleaseIdentifier` = `2.1.1-p01`

Yes, that explains why their precedence is always lower that the main version.

> For instance for version 2.1.2 you could stard with 2.1.2-p01 instead of 2.1.2 alone.

Ok, then we only release pre-release versions, without having a stable version.
Hmm, that might work, but would also need a stability lowering to dev, right? 
Composer wouldn't resolve to higher pre-release versions, if you resolve with "stable".

Sidenote: i think we won't get a 2.1.2 release of PhantomJS. 
The PhantomJS project has no maintainer and is pretty much dead. 
The community will not step in, because it's C++/Qt and hard to build.

I think there will be tech transition to Chrome in headless mode, when it becomes stable cross-platform.
There was also a fork using Phantom on top of Chromium Embedded Framework (CEF).

**Comment by gsouf** [comment]
@jakoch thanks for the details, I didn't notice the plus sign. Not sure but I think that in our case that should be something like: ``2.1.1+1``

Yes I agree with you that phantomjs is slowly dying and there are only a few chances it gets news upgrades.

For the side note: In addition of headless chrome (that still lacks the maturity it deserves and has a few blocking bugs) there is slimerjs based on gecko (but I didn't try it by myself).
